on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with: 
                distribution: 'corretto'
                java-version: '21'
                cache: 'maven'
                cache-dependency-path: 'pom.xml'
              name: Build with Maven
            - run: mvn package
            - run: mkdir target/libs && cp target/calc-0.1-jar-with-dependencies.jar target/libs
            - run: jlink --add-modules java.base,java.desktop --output target/custom-jre
            - run: jpackage -t app-image --input target/libs --main-jar calc-0.1-jar-with-dependencies.jar --runtime-image target/custom-jre --dest target/output
            - uses: actions/upload-artifact@v4
              with:
                name: packaging
                path: target/output
            # - run: mkdir staging && cp target/*.jar staging
            # - uses: actions/upload-artifact@v4
            #   with:
            #     name: package
            #     path: staging